/-
Copyright (c) 2026 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.CategoryTheory.Limits.FormalCoproducts.Cech
public import Mathlib.CategoryTheory.Subfunctor.Sieves
public import Mathlib.CategoryTheory.ShrinkYoneda

/-!
# ???

-/

@[expose] public section

universe w v u

namespace CategoryTheory

open Limits

variable {C : Type u} [Category.{v} C] [LocallySmall.{w} C] [HasFiniteProducts C]

namespace Limits.FormalCoproduct

/-- The augmented simplicial Cech presheaf of types attached to `U : FormalCoproduct.{w} C`,
the target of the augmentation is the subfunctor of the constant functor `Cᵒᵖ ⥤ Type w`
with value `PUnit` that is generated by the objects `U.obj`. -/
noncomputable def shrinkYonedaCech (U : FormalCoproduct.{w} C) :
    SimplicialObject.Augmented (Cᵒᵖ ⥤ Type w) where
  left := ((SimplicialObject.whiskering _ _).obj
      ((FormalCoproduct.eval.{w} C _).obj shrinkYoneda.{w})).obj U.cech
  right := (Subfunctor.ofObjects.{w} U.obj).toFunctor
  hom :=
    { app n :=
      { app V v := ⟨.unit, by
          obtain ⟨⟨i⟩, v, rfl⟩ := Types.jointly_surjective_of_isColimit
            (isColimitOfPreserves ((evaluation _ _).obj V) (coproductIsCoproduct _)) v
          let φ : Opposite.unop V ⟶ U.obj (i 0) :=
            shrinkYonedaObjObjEquiv v ≫ Pi.π _ 0
          simp [Subfunctor.ofObjects_obj_eq_univ φ] ⟩ } }

end Limits.FormalCoproduct

end CategoryTheory
